permalink: /:categories/:title/
sass:
  style: compressed
markdown: kramdown
kramdown:
    auto_ids: true
# URLs, etc
emailGeneralInquiry: "mailto:hello@mariannemakeup.com?subject=%20General%20inquiry"
emailBridalInquiry: "mailto:hello@mariannemakeup.com?subject=%20Bridal%20inquiry"
instagramURL: "https://instagram.com/mmoore_makeup"