permalink: /:categories/:title/
sass:
  style: compressed
markdown: kramdown
kramdown:
    auto_ids: true
# URLs, etc
emailGeneralInquiry: "mailto:hello@mariannemakeup.com?subject=%20General%20inquiry"
emailBridalInquiry: "mailto:hello@mariannemakeup.com?subject=%20Bridal%20inquiry"
instagramURL: "https://instagram.com/mariannemoore_makeup"
calendlyLesson: "https://calendly.com/mariannemakeup/makeup-lesson"
calendlyBridalLesson: "https://calendly.com/mariannemakeup/bridal-makeup-lesson"
calendlyConsultation: "https://calendly.com/mariannemakeup/30min"