bridal:
  - service: Bridal Makeup (Trial)
    cost: $150
    description:
  - service: Bridal Makeup (Day of)
    cost: $250
    description:
  - service: Bridal Party Makeup (Trial)
    cost: $150
    description:
  - service: Bridal Party Makeup (Day of)
    cost: $150
    description:
general:
  - service: Special occasion makeup
    cost: $150
    description:
  - service: Commercial rate (4hrs)
    cost: $475
    description: 
  - service: Commercial rate (8hrs)
    cost: $850
    description: 
  - service: Individual / Group lessons (2hrs)
    cost: $250
    description:
additional:
  - service: Travel
    cost:
    description: |
      If the total journey time exceeds 2hrs an additional fee of <strong>$100/hr</strong> will be applied.
  - service: Early morning
    cost: 
    description: |
      If the call time is before 8am an additional fee of <strong>$150</strong> will be applied. 
